import { TicketStatus, Priority, Technician } from './types';

export const STATUS_COLORS: Record<TicketStatus, string> = {
  [TicketStatus.PENDING]: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  [TicketStatus.IN_PROGRESS]: 'bg-blue-100 text-blue-800 border-blue-200',
  [TicketStatus.AWAITING_PARTS]: 'bg-purple-100 text-purple-800 border-purple-200',
  [TicketStatus.READY]: 'bg-green-100 text-green-800 border-green-200',
  [TicketStatus.FINISHED]: 'bg-gray-100 text-gray-800 border-gray-200',
  [TicketStatus.CANCELLED]: 'bg-red-100 text-red-800 border-red-200',
};

export const PRIORITY_COLORS: Record<Priority, string> = {
  [Priority.LOW]: 'text-gray-500',
  [Priority.MEDIUM]: 'text-blue-500',
  [Priority.HIGH]: 'text-orange-500',
  [Priority.URGENT]: 'text-red-600 font-bold',
};

export const MOCK_TECHNICIANS: Technician[] = [
  { id: 'T-001', name: 'Filipe Oliveira', role: 'Diretor de Obra', location: 'Braga', activeOrders: 3 },
  { id: 'T-002', name: 'Ricardo Gonçalves', role: 'Eletricista', location: 'Braga', activeOrders: 1 },
  { id: 'T-003', name: 'Susana Sousa', role: 'Administrativa', location: 'Braga', activeOrders: 0 },
  { id: 'T-004', name: 'Hirlan Silva', role: 'Ajudante Fotovoltaico', location: 'Braga', activeOrders: 2 },
  { id: 'T-005', name: 'ANDRESON SILVA', role: 'ELETRICISTA', location: 'Braga', activeOrders: 1 },
];

export const MOCK_TICKETS = [
  {
    id: 'OS-001',
    customerId: '1',
    customerName: 'João Silva',
    technicianId: 'T-001',
    technicianName: 'Filipe Oliveira',
    deviceType: 'Fotovoltaicos',
    deviceBrand: 'Huawei',
    deviceModel: 'SUN2000-100KTL',
    problemDescription: 'Comissionamento e verificação de strings em central fotovoltaica de grande escala.',
    status: TicketStatus.IN_PROGRESS,
    priority: Priority.URGENT,
    createdAt: '2023-10-25T10:30:00Z',
  },
  {
    id: 'OS-002',
    customerId: '2',
    customerName: 'Maria Santos',
    technicianId: 'T-002',
    technicianName: 'Ricardo Gonçalves',
    deviceType: 'Carregadores Veiculos elétricos',
    deviceBrand: 'Weg',
    deviceModel: 'WEMOB Wall',
    problemDescription: 'Não inicia carga no veículo, LED vermelho piscando.',
    status: TicketStatus.IN_PROGRESS,
    priority: Priority.MEDIUM,
    createdAt: '2023-10-26T14:20:00Z',
  },
  {
    id: 'OS-003',
    customerId: '3',
    customerName: 'Pedro Souza',
    technicianId: 'T-004',
    technicianName: 'Hirlan Silva',
    deviceType: 'Elétrica',
    deviceBrand: 'Schneider',
    deviceModel: 'iK60N',
    problemDescription: 'Curto-circuito intermitente no quadro principal.',
    status: TicketStatus.PENDING,
    priority: Priority.URGENT,
    createdAt: '2023-10-27T09:00:00Z',
  },
  {
    id: 'OS-004',
    customerId: '4',
    customerName: 'Carlos Ferreira',
    technicianId: 'T-005',
    technicianName: 'ANDRESON SILVA',
    deviceType: 'Fotovoltaicos',
    deviceBrand: 'Victron',
    deviceModel: 'MultiPlus-II',
    problemDescription: 'Sistema não entra em modo de bateria durante falha de rede.',
    status: TicketStatus.AWAITING_PARTS,
    priority: Priority.HIGH,
    createdAt: '2023-10-28T11:15:00Z',
  },
  {
    id: 'OS-005',
    customerId: '5',
    customerName: 'Condomínio Braga Lux',
    technicianId: 'T-001',
    technicianName: 'Filipe Oliveira',
    deviceType: 'Elétrica',
    deviceBrand: 'ABB',
    deviceModel: 'Emax 2',
    problemDescription: 'Vistoria técnica de segurança e auditoria energética em quadro de baixa tensão.',
    status: TicketStatus.PENDING,
    priority: Priority.HIGH,
    createdAt: '2023-10-29T08:45:00Z',
  },
  {
    id: 'OS-006',
    customerId: '6',
    customerName: 'Indústria MetalBraga',
    technicianId: 'T-001',
    technicianName: 'Filipe Oliveira',
    deviceType: 'Fotovoltaicos',
    deviceBrand: 'SMA',
    deviceModel: 'Sunny Highpower PEAK 3',
    problemDescription: 'Planeamento e supervisão de expansão de parque fotovoltaico industrial (500kWp).',
    status: TicketStatus.PENDING,
    priority: Priority.URGENT,
    createdAt: '2023-10-30T14:00:00Z',
  },
];